import { Question } from "./types";

export const questions: Question[] = [
  // === HISTOIRE ===
  {
    id: 1,
    category: "Histoire",
    difficulty: "easy",
    question: "En quelle année la Révolution française a-t-elle commencé ?",
    options: ["1776", "1789", "1799", "1815"],
    correctIndex: 1,
    explanation: "La Révolution française débuta en 1789 avec la prise de la Bastille le 14 juillet.",
  },
  {
    id: 2,
    category: "Histoire",
    difficulty: "medium",
    question: "Quel pharaon a fait construire la grande pyramide de Gizeh ?",
    options: ["Ramsès II", "Toutânkhamon", "Khéops", "Cléopâtre"],
    correctIndex: 2,
    explanation: "La grande pyramide de Gizeh fut construite pour le pharaon Khéops vers 2560 av. J.-C.",
  },
  {
    id: 3,
    category: "Histoire",
    difficulty: "medium",
    question: "Quel empire était gouverné par Gengis Khan au XIIIe siècle ?",
    options: ["Empire ottoman", "Empire mongol", "Empire romain", "Empire perse"],
    correctIndex: 1,
    explanation: "Gengis Khan fonda et dirigea l'Empire mongol, le plus grand empire contigu de l'histoire.",
  },
  {
    id: 4,
    category: "Histoire",
    difficulty: "hard",
    question: "Lors de quelle bataille Napoléon fut-il définitivement vaincu en 1815 ?",
    options: ["Bataille d'Austerlitz", "Bataille de Trafalgar", "Bataille de Waterloo", "Bataille de Leipzig"],
    correctIndex: 2,
    explanation: "La bataille de Waterloo, le 18 juin 1815, marque la défaite définitive de Napoléon.",
  },
  {
    id: 5,
    category: "Histoire",
    difficulty: "easy",
    question: "Qui était le premier président des États-Unis ?",
    options: ["Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin", "George Washington"],
    correctIndex: 3,
    explanation: "George Washington fut le premier président des États-Unis de 1789 à 1797.",
  },
  {
    id: 6,
    category: "Histoire",
    difficulty: "hard",
    question: "En quelle année le mur de Berlin a-t-il été construit ?",
    options: ["1955", "1958", "1961", "1968"],
    correctIndex: 2,
    explanation: "Le mur de Berlin fut construit en août 1961 pour séparer Berlin-Est de Berlin-Ouest.",
  },
  {
    id: 7,
    category: "Histoire",
    difficulty: "medium",
    question: "Quelle civilisation a inventé l'écriture cunéiforme ?",
    options: ["Égyptiens", "Sumériens", "Grecs", "Phéniciens"],
    correctIndex: 1,
    explanation: "Les Sumériens de Mésopotamie inventèrent l'écriture cunéiforme vers 3400 av. J.-C.",
  },
  {
    id: 8,
    category: "Histoire",
    difficulty: "easy",
    question: "Durant quelle guerre la bombe atomique fut-elle utilisée pour la première fois ?",
    options: ["Première Guerre mondiale", "Guerre de Corée", "Guerre du Vietnam", "Seconde Guerre mondiale"],
    correctIndex: 3,
    explanation: "Les bombes atomiques furent lâchées sur Hiroshima et Nagasaki en août 1945 durant la Seconde Guerre mondiale.",
  },

  // === SCIENCES ===
  {
    id: 9,
    category: "Sciences",
    difficulty: "easy",
    question: "Quelle est la formule chimique de l'eau ?",
    options: ["HO", "H2O", "H3O", "OH2"],
    correctIndex: 1,
    explanation: "L'eau est composée de deux atomes d'hydrogène et d'un atome d'oxygène : H₂O.",
  },
  {
    id: 10,
    category: "Sciences",
    difficulty: "medium",
    question: "Quelle planète est la plus grande du système solaire ?",
    options: ["Saturne", "Neptune", "Jupiter", "Uranus"],
    correctIndex: 2,
    explanation: "Jupiter est la plus grande planète du système solaire, avec un diamètre 11 fois celui de la Terre.",
  },
  {
    id: 11,
    category: "Sciences",
    difficulty: "hard",
    question: "Quel est le numéro atomique de l'or ?",
    options: ["47", "79", "82", "92"],
    correctIndex: 1,
    explanation: "L'or (Au) a le numéro atomique 79 dans le tableau périodique des éléments.",
  },
  {
    id: 12,
    category: "Sciences",
    difficulty: "medium",
    question: "À quelle vitesse environ la lumière voyage-t-elle dans le vide ?",
    options: ["150 000 km/s", "300 000 km/s", "450 000 km/s", "600 000 km/s"],
    correctIndex: 1,
    explanation: "La lumière voyage à environ 299 792 km/s dans le vide, soit approximativement 300 000 km/s.",
  },
  {
    id: 13,
    category: "Sciences",
    difficulty: "easy",
    question: "Quel scientifique a formulé la théorie de la relativité ?",
    options: ["Isaac Newton", "Stephen Hawking", "Albert Einstein", "Niels Bohr"],
    correctIndex: 2,
    explanation: "Albert Einstein publia la théorie de la relativité restreinte en 1905 et générale en 1915.",
  },
  {
    id: 14,
    category: "Sciences",
    difficulty: "hard",
    question: "Combien d'os comporte le corps humain adulte ?",
    options: ["186", "206", "236", "256"],
    correctIndex: 1,
    explanation: "Le corps humain adulte comporte 206 os, contre environ 270 à la naissance.",
  },
  {
    id: 15,
    category: "Sciences",
    difficulty: "medium",
    question: "Quel gaz est le plus abondant dans l'atmosphère terrestre ?",
    options: ["Oxygène", "Dioxyde de carbone", "Argon", "Azote"],
    correctIndex: 3,
    explanation: "L'azote (N₂) représente environ 78% de l'atmosphère terrestre.",
  },
  {
    id: 16,
    category: "Sciences",
    difficulty: "easy",
    question: "Quelle est l'unité de mesure de la fréquence ?",
    options: ["Newton", "Hertz", "Pascal", "Joule"],
    correctIndex: 1,
    explanation: "Le Hertz (Hz) est l'unité SI de fréquence, représentant un cycle par seconde.",
  },

  // === ARTS & LITTÉRATURE ===
  {
    id: 17,
    category: "Arts & Littérature",
    difficulty: "easy",
    question: "Qui a peint la Joconde ?",
    options: ["Michelange", "Raphaël", "Léonard de Vinci", "Botticelli"],
    correctIndex: 2,
    explanation: "La Joconde (ou Mona Lisa) fut peinte par Léonard de Vinci entre 1503 et 1519.",
  },
  {
    id: 18,
    category: "Arts & Littérature",
    difficulty: "medium",
    question: "Quel mouvement artistique Picasso a-t-il co-fondé ?",
    options: ["Impressionnisme", "Surréalisme", "Cubisme", "Expressionnisme"],
    correctIndex: 2,
    explanation: "Pablo Picasso et Georges Braque co-fondèrent le Cubisme au début du XXe siècle.",
  },
  {
    id: 19,
    category: "Arts & Littérature",
    difficulty: "medium",
    question: "Dans quelle ville se trouve le musée du Louvre ?",
    options: ["Rome", "Londres", "Madrid", "Paris"],
    correctIndex: 3,
    explanation: "Le musée du Louvre est situé à Paris, France, et est l'un des plus grands musées du monde.",
  },
  {
    id: 20,
    category: "Arts & Littérature",
    difficulty: "hard",
    question: "Qui a composé la symphonie n°9 en ré mineur ?",
    options: ["Mozart", "Bach", "Beethoven", "Schubert"],
    correctIndex: 2,
    explanation: "Ludwig van Beethoven composa sa 9e symphonie en 1824, alors qu'il était sourd.",
  },
  {
    id: 21,
    category: "Arts & Littérature",
    difficulty: "easy",
    question: "Quel auteur a écrit 'Les Misérables' ?",
    options: ["Émile Zola", "Victor Hugo", "Gustave Flaubert", "Alexandre Dumas"],
    correctIndex: 1,
    explanation: "Victor Hugo publia 'Les Misérables' en 1862, l'un des plus grands romans de la littérature française.",
  },
  {
    id: 22,
    category: "Arts & Littérature",
    difficulty: "hard",
    question: "Quel est le vrai nom de Molière ?",
    options: ["Jean-Baptiste Poquelin", "François-Marie Arouet", "Pierre-Augustin Caron", "Nicolas Boileau"],
    correctIndex: 0,
    explanation: "Molière est le nom de scène de Jean-Baptiste Poquelin, dramaturge français du XVIIe siècle.",
  },
  {
    id: 23,
    category: "Arts & Littérature",
    difficulty: "medium",
    question: "Quel style architectural caractérise la cathédrale Notre-Dame de Paris ?",
    options: ["Roman", "Baroque", "Gothique", "Renaissance"],
    correctIndex: 2,
    explanation: "Notre-Dame de Paris est un chef-d'œuvre de l'architecture gothique, construite entre 1163 et 1345.",
  },
  {
    id: 24,
    category: "Arts & Littérature",
    difficulty: "easy",
    question: "Quel artiste néerlandais est célèbre pour 'La Nuit étoilée' ?",
    options: ["Rembrandt", "Vermeer", "Van Gogh", "Mondrian"],
    correctIndex: 2,
    explanation: "Vincent van Gogh peignit 'La Nuit étoilée' en 1889 depuis l'asile de Saint-Rémy-de-Provence.",
  },

  // === SPORT ===
  {
    id: 25,
    category: "Sport",
    difficulty: "easy",
    question: "Combien de joueurs compte une équipe de football ?",
    options: ["9", "10", "11", "12"],
    correctIndex: 2,
    explanation: "Une équipe de football est composée de 11 joueurs sur le terrain.",
  },
  {
    id: 26,
    category: "Sport",
    difficulty: "medium",
    question: "Dans quel pays les Jeux Olympiques modernes ont-ils été créés ?",
    options: ["France", "États-Unis", "Grèce", "Angleterre"],
    correctIndex: 2,
    explanation: "Les Jeux Olympiques modernes furent fondés par Pierre de Coubertin et les premiers eurent lieu à Athènes, Grèce, en 1896.",
  },
  {
    id: 27,
    category: "Sport",
    difficulty: "medium",
    question: "Quel pays a remporté le plus de Coupes du Monde de football ?",
    options: ["Allemagne", "Argentine", "Brésil", "Italie"],
    correctIndex: 2,
    explanation: "Le Brésil est le pays le plus titré en Coupe du Monde avec 5 victoires.",
  },
  {
    id: 28,
    category: "Sport",
    difficulty: "hard",
    question: "Quel est le record du monde du 100m masculin et par qui est-il détenu ?",
    options: ["9.58s - Usain Bolt", "9.69s - Tyson Gay", "9.72s - Asafa Powell", "9.63s - Justin Gatlin"],
    correctIndex: 0,
    explanation: "Usain Bolt a établi le record du monde du 100m en 9.58 secondes aux Mondiaux de Berlin en 2009.",
  },
  {
    id: 29,
    category: "Sport",
    difficulty: "easy",
    question: "Quel sport se joue à Wimbledon ?",
    options: ["Cricket", "Golf", "Tennis", "Polo"],
    correctIndex: 2,
    explanation: "Wimbledon est le plus ancien tournoi de tennis du monde, disputé à Londres depuis 1877.",
  },
  {
    id: 30,
    category: "Sport",
    difficulty: "medium",
    question: "Quelle nageuse française a remporté plusieurs médailles d'or olympiques ?",
    options: ["Laure Manaudou", "Camille Muffat", "Florent Manaudou", "Charlotte Bonnet"],
    correctIndex: 0,
    explanation: "Laure Manaudou a notamment remporté l'or olympique sur le 400m nage libre aux JO d'Athènes 2004.",
  },
  {
    id: 31,
    category: "Sport",
    difficulty: "hard",
    question: "En quelle année le Tour de France a-t-il été créé ?",
    options: ["1895", "1903", "1910", "1920"],
    correctIndex: 1,
    explanation: "Le Tour de France fut créé en 1903 à l'initiative du journal L'Auto.",
  },
  {
    id: 32,
    category: "Sport",
    difficulty: "easy",
    question: "Quel sport pratique Rafael Nadal ?",
    options: ["Golf", "Football", "Tennis", "Squash"],
    correctIndex: 2,
    explanation: "Rafael Nadal est un joueur de tennis espagnol, l'un des plus grands champions de tous les temps.",
  },
];

export const categoryColors: Record<string, { bg: string; text: string; border: string; icon: string }> = {
  Histoire: {
    bg: "bg-amber-500/20",
    text: "text-amber-400",
    border: "border-amber-500/30",
    icon: "🏛️",
  },
  Sciences: {
    bg: "bg-cyan-500/20",
    text: "text-cyan-400",
    border: "border-cyan-500/30",
    icon: "🔬",
  },
  Géographie: {
    bg: "bg-blue-500/20",
    text: "text-blue-400",
    border: "border-blue-500/30",
    icon: "🌍",
  },
  "Pop Culture": {
    bg: "bg-pink-500/20",
    text: "text-pink-400",
    border: "border-pink-500/30",
    icon: "🎬",
  },
  Sport: {
    bg: "bg-green-500/20",
    text: "text-green-400",
    border: "border-green-500/30",
    icon: "⚡",
  },
  "Arts & Littérature": {
    bg: "bg-purple-500/20",
    text: "text-purple-400",
    border: "border-purple-500/30",
    icon: "🎨",
  },
  "Nature & Animaux": {
    bg: "bg-emerald-500/20",
    text: "text-emerald-400",
    border: "border-emerald-500/30",
    icon: "🌿",
  },
  Technologie: {
    bg: "bg-indigo-500/20",
    text: "text-indigo-400",
    border: "border-indigo-500/30",
    icon: "💻",
  },
  Gastronomie: {
    bg: "bg-orange-500/20",
    text: "text-orange-400",
    border: "border-orange-500/30",
    icon: "🍽️",
  },
  "Mythologie & Religions": {
    bg: "bg-violet-500/20",
    text: "text-violet-400",
    border: "border-violet-500/30",
    icon: "⚡",
  },
  Cinéma: {
    bg: "bg-red-500/20",
    text: "text-red-400",
    border: "border-red-500/30",
    icon: "🎬",
  },
  Musique: {
    bg: "bg-fuchsia-500/20",
    text: "text-fuchsia-400",
    border: "border-fuchsia-500/30",
    icon: "🎵",
  },
  "Économie & Business": {
    bg: "bg-teal-500/20",
    text: "text-teal-400",
    border: "border-teal-500/30",
    icon: "💰",
  },
  "Espace & Astronomie": {
    bg: "bg-sky-500/20",
    text: "text-sky-400",
    border: "border-sky-500/30",
    icon: "🚀",
  },
  Philosophie: {
    bg: "bg-rose-500/20",
    text: "text-rose-400",
    border: "border-rose-500/30",
    icon: "🤔",
  },
  "Maîtrise du Français": {
    bg: "bg-blue-600/20",
    text: "text-blue-300",
    border: "border-blue-500/30",
    icon: "📝",
  },
  "Actualités 2025-2026": {
    bg: "bg-lime-500/20",
    text: "text-lime-400",
    border: "border-lime-500/30",
    icon: "📰",
  },
  "Vocabulaire des Jeunes": {
    bg: "bg-pink-500/20",
    text: "text-pink-300",
    border: "border-pink-500/30",
    icon: "🗣️",
  },
};

export const difficultyColors = {
  easy: { text: "text-green-400", label: "Facile" },
  medium: { text: "text-yellow-400", label: "Moyen" },
  hard: { text: "text-rose-400", label: "Difficile" },
};
